/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.vaj.shoppingcart;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    
    @Test public void testAppHasNoGreeting() {
        App classUnderTest = new App();
        assertNull("app shouldn't have a greeting", classUnderTest.getGreeting());
    }
}
